### ISSUE TITLE
Update Color Scheme

### ISSUE THREAD

**Issue by JaynaMMenard** [JaynaMMenard/WebSiteTTP#1]
#1 Use this to change the colors of the about page. Its the same Color Scheme for the whole website.

**LINK:**
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwi9itqqq-bmAhVqUN8KHfY9C9wQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.schemecolor.com%2Fblue-eyes-color-palette.php&psig=AOvVaw1wjmruRVwEajfzrjli9lAY&ust=1578103361309829

**Comment by Brandon-Vasquez** [comment]
Color scheme update complete.
